FROM python:3.7

WORKDIR /usr/src/app

RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python - \
    && export PATH="/root/.local/bin:$PATH"
ENV PATH "/root/.local/bin:$PATH"



# Build image
# sudo docker build -t scenic-test -f ./Dockerfile-test .

# run bash on container
# sudo docker run --name scenic-mount -it --rm -v /home/cloud/arenb/Scenic:/usr/src/app scenic-test bash
# sudo docker run --name sc-dev-arenb -it -v /home/cloud/arenb/Scenic:/usr/src/app scenic-catriona bash

# poetry install

# bash runAllMeasurements.sh

# sudo docker start sc-dev-arenb ; sudo docker attach sc-dev-arenb
