FROM python:3.7

WORKDIR /usr/src/app

RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python - \
    && export PATH="/root/.local/bin:$PATH"
ENV PATH "/root/.local/bin:$PATH"



# Build image
# sudo docker build -t scenic-test -f ./Dockerfile-test .

# run bash on container
# sudo docker run --name scenic-mount -it --rm -v /home/cloud/catrionam/Scenic:/usr/src/app scenic-catriona bash

# bash runAllMeasurements.sh